M48
; DRILL file KiCad 10.0.6 date 2026-09-24T22:10:38
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-24T22:10:38-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.100
%
G90
G05
T1
X176.85Y-64.56
X176.85Y-70.34
T2
X125.74Y-55.22
X125.74Y-67.12
M30
